FROM node as builder
WORKDIR /usr/app
COPY ./package.json ./
RUN npm install 
COPY . .
RUN npm run build

FROM nginx
COPY ./nginxProduction/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /usr/app/dist /usr/share/nginx/html
CMD bin/bash -c "envsubst '\$PORT' < /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf" && nginx -g "daemon off;"