sudo: required
language: node_js
node_js:
    - "9"
services:
    - docker
before_install:
    - wget -qO- https://toolbelt.heroku.com/install.sh | sh
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
script:
    - docker build -t $DOCKER_USERNAME/api -f ./api/Dockerfile.prod ./api;
    - docker tag $DOCKER_USERNAME/api registry.heroku.app/$HEROKU_APP_API/web;
    - docker build -t $DOCKER_USERNAME/client -f ./client/Dockerfile.prod ./client;
    - docker tag $DOCKER_USERNAME/client registry.heroku.app/$HEROKU_APP_CLIENT/web;
    - docker build -t $DOCKER_USERNAME/nginx -f ./nginx/prod/Dockerfile.prod ./nginx/prod;
    - docker tag $DOCKER_USERNAME/nginx registry.heroku.app/$HEROKU_APP_NGINX/web;
deploy:
    provider: script
    script:
        docker push $DOCKER_USERNAME/api;
        docker push registry.heroku.app/$HEROKU_APP_API/web;
        heroku container:release web --app $HEROKU_APP_API;
        docker push $DOCKER_USERNAME/client;
        docker push registry.heroku.app/$HEROKU_APP_CLIENT/web;
        heroku container:release web --app $HEROKU_APP_CLIENT;
        docker push $DOCKER_USERNAME/nginx;
        docker push registry.heroku.app/$HEROKU_APP_NGINX/web;
        heroku container:release web --app $HEROKU_APP_NGINX;
    branch:
        master