FROM nginx:stable
COPY ./default.template /etc/nginx/conf.d/default.template
CMD bin/bash -c "envsubst '\$API_URL \$CLIENT_URL' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf" && nginx -g "daemon off;"