FROM nginx:stable
COPY ./default.template /etc/nginx/conf.d/default.template
CMD bin/bash -c "envsubst '\$HEROKU_API_URL \$HEROKU_CLIENT_URL \$PORT' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf" && nginx -g "daemon off;"